apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: yousirs-app
  labels:
    name: yousirs-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: yousirs-app
    spec:
      containers:
      - name: yousirs-app
        image: joelintheory/yousirs
        env:
        - name: database-url
          valueFrom:
            secretKeyRef:
              name: database-url
              key: connection_string
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
          hostPort: 5000
      restartPolicy: Always
